# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import src.hide_and_seek_pb2 as hide__and__seek__pb2


class GameHandlerStub(object):
    """*
    The service of the game

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DeclareReadiness = channel.unary_unary(
                '/ir.sharif.aic.hideandseek.api.grpc.GameHandler/DeclareReadiness',
                request_serializer=hide__and__seek__pb2.DeclareReadinessCommand.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.Watch = channel.unary_stream(
                '/ir.sharif.aic.hideandseek.api.grpc.GameHandler/Watch',
                request_serializer=hide__and__seek__pb2.WatchCommand.SerializeToString,
                response_deserializer=hide__and__seek__pb2.GameView.FromString,
                )
        self.Move = channel.unary_unary(
                '/ir.sharif.aic.hideandseek.api.grpc.GameHandler/Move',
                request_serializer=hide__and__seek__pb2.MoveCommand.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.SendMessage = channel.unary_unary(
                '/ir.sharif.aic.hideandseek.api.grpc.GameHandler/SendMessage',
                request_serializer=hide__and__seek__pb2.ChatCommand.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class GameHandlerServicer(object):
    """*
    The service of the game

    """

    def DeclareReadiness(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Watch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Move(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GameHandlerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DeclareReadiness': grpc.unary_unary_rpc_method_handler(
                    servicer.DeclareReadiness,
                    request_deserializer=hide__and__seek__pb2.DeclareReadinessCommand.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Watch': grpc.unary_stream_rpc_method_handler(
                    servicer.Watch,
                    request_deserializer=hide__and__seek__pb2.WatchCommand.FromString,
                    response_serializer=hide__and__seek__pb2.GameView.SerializeToString,
            ),
            'Move': grpc.unary_unary_rpc_method_handler(
                    servicer.Move,
                    request_deserializer=hide__and__seek__pb2.MoveCommand.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=hide__and__seek__pb2.ChatCommand.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ir.sharif.aic.hideandseek.api.grpc.GameHandler', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GameHandler(object):
    """*
    The service of the game

    """

    @staticmethod
    def DeclareReadiness(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ir.sharif.aic.hideandseek.api.grpc.GameHandler/DeclareReadiness',
            hide__and__seek__pb2.DeclareReadinessCommand.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Watch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ir.sharif.aic.hideandseek.api.grpc.GameHandler/Watch',
            hide__and__seek__pb2.WatchCommand.SerializeToString,
            hide__and__seek__pb2.GameView.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Move(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ir.sharif.aic.hideandseek.api.grpc.GameHandler/Move',
            hide__and__seek__pb2.MoveCommand.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ir.sharif.aic.hideandseek.api.grpc.GameHandler/SendMessage',
            hide__and__seek__pb2.ChatCommand.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
